<?php

namespace ContainerOQKPTWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GcGfJ6KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gcGfJ6K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gcGfJ6K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'announcement' => ['privates', '.errored..service_locator.gcGfJ6K.App\\Entity\\Announcement', NULL, 'Cannot autowire service ".service_locator.gcGfJ6K": it references class "App\\Entity\\Announcement" but no such service exists.'],
        ], [
            'announcement' => 'App\\Entity\\Announcement',
        ]);
    }
}
