<?php

namespace ContainerOQKPTWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGarageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RhCUUGL.App\Entity\Garage' shared service.
     *
     * @return \App\Entity\Garage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RhCUUGL": it references class "App\\Entity\\Garage" but no such service exists.');
    }
}
