<?php

namespace ContainerOQKPTWT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NI.jnw2.App\Entity\Professionnal' shared service.
     *
     * @return \App\Entity\Professionnal
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NI.jnw2": it references class "App\\Entity\\Professionnal" but no such service exists.');
    }
}
