<?php

namespace ContainerARnjGHx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NI_Jnw2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NI.jnw2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NI.jnw2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'professionnal' => ['privates', '.errored..service_locator.NI.jnw2.App\\Entity\\Professionnal', NULL, 'Cannot autowire service ".service_locator.NI.jnw2": it references class "App\\Entity\\Professionnal" but no such service exists.'],
        ], [
            'professionnal' => 'App\\Entity\\Professionnal',
        ]);
    }
}
