<?php

namespace ContainerARnjGHx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FhA5lhVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FhA5lhV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FhA5lhV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'professionnalRepository' => ['privates', 'App\\Repository\\ProfessionnalRepository', 'getProfessionnalRepositoryService', true],
        ], [
            'professionnalRepository' => 'App\\Repository\\ProfessionnalRepository',
        ]);
    }
}
