<?php

namespace ContainerARnjGHx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnouncementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gcGfJ6K.App\Entity\Announcement' shared service.
     *
     * @return \App\Entity\Announcement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gcGfJ6K": it references class "App\\Entity\\Announcement" but no such service exists.');
    }
}
