<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \App\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'ligne_1', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'ligne_2', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'ligne_3', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'postalCode', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'city'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'ligne_1', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'ligne_2', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'ligne_3', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'postalCode', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'city'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getLigne1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigne1', []);

        return parent::getLigne1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigne1(string $ligne_1): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigne1', [$ligne_1]);

        return parent::setLigne1($ligne_1);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigne2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigne2', []);

        return parent::getLigne2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigne2(?string $ligne_2): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigne2', [$ligne_2]);

        return parent::setLigne2($ligne_2);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigne3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigne3', []);

        return parent::getLigne3();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigne3(?string $ligne_3): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigne3', [$ligne_3]);

        return parent::setLigne3($ligne_3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode(string $postalCode): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postalCode]);

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(string $city): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

}
