<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Garage extends \App\Entity\Garage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'denomination', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'announcement', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'professionnal', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'address'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'denomination', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'announcement', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'professionnal', '' . "\0" . 'App\\Entity\\Garage' . "\0" . 'address'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Garage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDenomination(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDenomination', []);

        return parent::getDenomination();
    }

    /**
     * {@inheritDoc}
     */
    public function setDenomination(string $denomination): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDenomination', [$denomination]);

        return parent::setDenomination($denomination);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(string $phone): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', []);

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation(?string $observation): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', [$observation]);

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnouncement(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnouncement', []);

        return parent::getAnnouncement();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnnouncement(\App\Entity\Announcement $announcement): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnnouncement', [$announcement]);

        return parent::addAnnouncement($announcement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnnouncement(\App\Entity\Announcement $announcement): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnnouncement', [$announcement]);

        return parent::removeAnnouncement($announcement);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessionnal(): ?\App\Entity\Professionnal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessionnal', []);

        return parent::getProfessionnal();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessionnal(?\App\Entity\Professionnal $professionnal): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessionnal', [$professionnal]);

        return parent::setProfessionnal($professionnal);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?\App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(?\App\Entity\Address $address): \App\Entity\Garage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

}
